### ISSUE TITLE
"No module named proxy" error in Ubuntu 14.04

### ISSUE THREAD

**Issue by Rondo5000** [eliostvs/tomate-gtk#8] opened 2016-05-19 03:25 UTC
Hi.  Since updating to version 0.6.0 I get the following issue (I'll note that I've also done a full reinstall and purged the old PPA)

`Traceback (most recent call last):
  File "/usr/bin/tomate-gtk", line 9, in <module>
    load_entry_point('tomate-gtk==0.6.0', 'console_scripts', 'tomate-gtk')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/tomate_gtk/__main__.py", line 3, in <module>
    from .main import main
  File "/usr/lib/python2.7/dist-packages/tomate_gtk/main.py", line 22, in <module>
    from tomate.proxy import ProxyModule
ImportError: No module named proxy`

Thanks in advance for your help

**Comment by eliostvs** [comment] 2016-05-19 12:00
Hi. The problem is that the package python-tomate wasn't upgraded. I forgot to update the meta packages to force that. I will update the packages to force the upgrade of the package python-tomate. It should be fixed in a couple of hours. Thank you for the report.

**Comment by eliostvs** [comment] 2016-05-21 15:39
Hi. Do you still have the same problem?

**Comment by Rondo5000** [comment] 2016-05-22 03:06
Hello,

Nope, the problem is gone!  Thanks again! :)

**Comment by eliostvs** [comment] 2016-05-24 01:02
Great. I'm glad to hear that.

**Closed by eliostvs** 2016-05-24 01:02 UTC
Labels: bug
